language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - cmake --version
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. || exit $?
  - cmake --build . --config Debug || exit $?
