version: '{build}'

environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015 Win64"
    ARCH: 64
    PlatformToolset: v140
    Platform: x64
  - GENERATOR: "Visual Studio 12 2013 Win64"
    ARCH: 64
    PlatformToolset: v120
    Platform: x64

build_script:
- ps: |
    cmake --version

    mkdir build

    cd build

    cmake -DCMAKE_BUILD_TYPE=Debug -G"$env:GENERATOR" ..

    cmake --build . --config Debug
